#!/bin/bash
TEST_USER=${TEST_USER:-testuser}
TEST_PASSWORD=${TEST_PASSWORD:-testpassword}
SECRET_KEY=${SECRET_KEY:-foo}
SECRET_VALUE=${SECRET_VALUE:-zoo}
TOTP_PERIOD=${TOTP_PERIOD:-30}
TOTP_KEYSIZE=${TOTP_KEYSIZE:-30}
TOTP_ALGO=${TOTP_ALGO:-SHA1}
TOTP_DIGITS=${TOTP_DIGITS:-6}

# Enable the Userpass Auth Method
vault auth enable userpass

# Enable and configure the TOTP MFA method
vault write sys/mfa/method/totp/my_totp \
  issuer=Vault \
  period=${TOTP_PERIOD} \
  key_size=${TOTP_KEYSIZE} \
  algorithm=${TOTP_ALGO} \
  digits=${TOTP_DIGITS}

# Write a policy requiring TOTP MFA for Read Operation on a KV Path
vault policy write totp-policy -<<EOF
#Support both v1 and v2 paths
path "secret_new/${SECRET_KEY}" {
capabilities = ["read"]
mfa_methods  = ["my_totp"]
}
path "secret_new/data/${SECRET_KEY}" {
capabilities = ["read"]
mfa_methods  = ["my_totp"]
}
EOF

# Enable a new KV Secrets Engine with a custom path
vault secrets enable -path=secret_new kv

# Write data to the new KV path
vault kv put secret_new/${SECRET_KEY} password=${SECRET_VALUE}

# Create a new Userpass User and assign the TOTP MFA policy
vault write auth/userpass/users/${TEST_USER} password=${TEST_PASSWORD} policies=totp-policy

# Authenticate to Vault via Userpass and retrieve a Token
TOKEN=$(vault write -field=token auth/userpass/login/${TEST_USER} password=${TEST_PASSWORD})

# Perform a lookup on the Token to pull the associated Entity ID
ENTITY_ID=$(vault token lookup -format=json ${TOKEN} | jq -r .data.entity_id)

# Generate a new TOTP barcode using the extracted Entity ID 
BARCODE=$(vault write -field=barcode sys/mfa/method/totp/my_totp/admin-generate entity_id=${ENTITY_ID})

# Load the barcode URL into a browser and capture the resultant QR Code with the Microsoft Authenticator App
echo "Paste the following into your browser to generate the TOTP image to import into your MFA device e.g. Google Authenticator"

echo "data:image/png;base64,${BARCODE}"
echo

# Log out of root, log in via userpass, and perform a KV read operation using the six-digit code generated by the Microsoft Authenticator App
echo "Run the following commands to login and test"
cat <<EOF
unset VAULT_TOKEN
vault login -method=userpass username=${TEST_USER} password=${TEST_PASSWORD}
vault kv get -mfa=my_totp:${CODE} secret_new/${SECRET_KEY}
EOF
